### ISSUE TITLE
font mapping broken

### ISSUE THREAD

**Issue by shibumi** [gabrielelana/awesome-terminal-fonts#31]
Hello,
The last stable commit was fcfef52938f972b6595e4730b0b4c0eac0158bfa every commit after this is broken due to font mapping issues.
When I apply any other commit after this my zsh powerline seems broken. 

Screenshots:

Everything fine:
![..](https://paste.archlinux.de/Z7f/)

Broken:
![..](https://paste.archlinux.de/hvSy/)

I have no idea if this is the fault of zsh-theme-powerlevel9k or of awesome-terminal-fonts.

**Comment by shibumi** [comment]
And the devicon font mapping seems wrong also: (doesn't matter with which commit):

https://github.com/ryanoasis/vim-devicons/issues/173

**Comment by davidmpaz** [comment]
Is there any result with this issue? I just installed `powerlevel9k` theme with `awesome-terminal-fonts` and I  have icons swapped or repeated I guess. Here is my screen shot for `get_icon_names` execution.

![selection_074](https://cloud.githubusercontent.com/assets/210742/21134322/9c971432-c11d-11e6-897d-a26ff67f9abc.png)

Battery and Python missing and some others (AWS, SERVER) has the GitLab icon maybe?

Thanks in advance.

**Comment by gabrielelana** [comment]
I think that the explanation is in bhilburn/powerlevel9k#429 they are referring to codepoints instead of using font maps and this is a problem. Codepoints are simpler but since icon fonts use the private area codepoints have no meaning but the one given by the font author, the author can remove, rename, move a glyph because there's no standard to refer to, so I think font maps are the way to go

Moreover most of the icon fonts have `css` files that does the same job
