### ISSUE TITLE
installation difficulties on linux

### ISSUE THREAD

**Issue by Gy0m** [gabrielelana/awesome-terminal-fonts#53]
with solo user install and multi user install for powerline fonts i have 10-symbols.conf in multiple folders and i am getting lost about wich is effective. Also when you say "replacing PragmataPro with the name of the font you want to use in the terminal " you talk about one of the 4 fonts available in the .buid ?  I'm sorry it seems a stupid question but this is not obvious for me, and i have also to integrate it with Powerlevel9K that is not obvious too. I know when i'll succeed it i'll say it was obvious but now i'm lost and search a little help here after posting a lot of post in askUbuntu ^^

I'll delete this post as fast as i receive an answer that direct me a little as this is not a real issue .... sorry

**Comment by SharakPL** [comment]
I also find most of the instruction rather problematic for beginners. I ended up with conf.d files instead of directories. Instructions say what to do step by step but not how to do it and what command to use. Why bother with such instructions (copy this... copy that... run that... copy another) when all you need to do is:
1. `git clone https://github.com/gabrielelana/awesome-terminal-fonts.git`
2. `./awesome-terminal-fonts/install.sh`
4. update font name using simple editor like _vim_ or _nano_
`vi ~/.config/fontconfig/conf.d/10-symbols.conf`
and replace `PragmataPro` with `FontAwsome` (if that's the one you want to use)
3. `echo 'source ~/.fonts/*.sh' >> ~/.zshrc`

**Comment by blinkeye** [comment]
> ...
>    `vi ~/.config/fontconfig/conf.d/10-symbols.conf`
>    and replace `PragmataPro` with `FontAwsome` (if that's the one you want to use)
> ...

you meant to write: ... and replace `PragmataPro` with `FontAwesome`. Thanks for the instructions, overlooked the handy install script :+1:

**Comment by SharakPL** [comment]
@blinkeye thanks, fixed
