### ISSUE TITLE
Applying font fallback on Mac OS X?

### ISSUE THREAD

**Issue by andreafrancia** [gabrielelana/awesome-terminal-fonts#7]
I wish to use Pomicons on iTerm2 in Mac OS X.

If understood correctly I need to copy fonts from `build` to `~/Library/Fonts` (instead of to `~/.fonts`).

But I'm not sure where to put the `10-symbols.conf`, provided that Mac OS X font system can understand this `fontconfig` file.

For now I'm working around this issue using the "Non-ASCII Font" fallback of iTerm2 but this is not a very good solution as you can add only just one font alternative.

I know about nothing about Fonts and how Fonts works on Mac OS X, and I'm also having some difficult in understand what to search on Google to find a solution, any help will be appreciated.

**Comment by gabrielelana** [comment]
I don’t think that the OS X font system works that way (I should specify in the README that the `How to install` section is specific to Linux freetype2)

Anyway, the magic words to search are _”OS X font fallback”_, with that I found:
- https://discussions.apple.com/thread/6509534
- http://apple.stackexchange.com/questions/71719/how-does-the-os-x-font-fallback-system-work

As far as I understood, you can configure the fallback fonts in the Plist located at /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Resources/DefaultFontFallbacks.plist

With `PlistBuddy` you can also automate the procedure if you want

Be mind, I don’t know if this will work but hopefully it will, otherwise it could be a starting point :smile:

**Comment by leoj3n** [comment]
You have to disable System Integrity Protection by rebooting and holding <kbd>CMD+R</kbd> and launching Terminal from the Utilities menu so you can run:

```
csrutil disable; reboot
```

Then you can use Xcode.app to open and edit the plist file after first copying it to `~/Desktop`:

```
cp /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Resources/DefaultFontFallbacks.plist ~/Desktop
```
```
open -a Xcode.app ~/Desktop/DefaultFontFallbacks.plist
```
In the plist editor, expand "monospace" then click the <kbd>+</kbd> icon to add a new row and type in `Pomodoro`. Do this three more times for `FontAwesome`, `Octicons`, and `Icomoon` until the plist looks like:

![image](https://cloud.githubusercontent.com/assets/990216/17275438/b7e8351e-56cd-11e6-9222-f18322b74aef.png)

Now reboot into recovery mode again (<kbd>CMD+R</kbd>) and re-enable System Integrity Protection:

```
csrutil disable; reboot
```

Works for me in iTerm2 Build 3.0.5 👍

**Comment by oblitum** [comment]
@leoj3n great, though, I must confess that is a painful process....
